import os

GROUP_ACCESS_TOKEN_KEY = "GROUP_ACCESS_TOKEN"
GROUP_ACCESS_TOKEN = os.environ.get(GROUP_ACCESS_TOKEN_KEY, None)

MY_GROUP_ID = 162927036
VK_API_VERSION = "5.131"

DATETIME_SAVE_FILE_NAME_FORMAT = '%d.%m.%Y'
DATETIME_TIME_INTERVAL_NAME_FORMAT = '%H:%M'
DATETIME_STANDARD_FORMAT = '%Y-%m-%d %H:%M:%S.%f'
DATETIME_STANDARD_FORMAT_WITHOUT_MILLISECONDS = '%Y-%m-%d %H:%M:%S'

MINUTES_INTERVAL = 2
MINUTES_INTERVALS_NUMBER = 24 * 60 // MINUTES_INTERVAL

SECRET_MESSAGE_LINE_ASKING_FOR_PASSWORD = "Please, give me a password to show my activity info."
SECRET_MESSAGE_LINE_ASKING_FOR_ACCOUNT_INFO = "Please, give me my account info."
